### ISSUE TITLE
Use tested versions of plugins, rather than clone from bleeding edge repo

### ISSUE THREAD

**Issue by ThorodanBrom** [pct960/vim-ide#1]
From a [comment on /r/vim](https://www.reddit.com/r/vim/comments/92a9y0/whats_your_honest_opinion_of_spacevim/e34np5i/)

> I never used a Vim distribution, but I have a feeling it could suffer from the same problem certain Emacs distributions - such as Spacemacs and Doom - could suffer from.
> 
> These type of projects have a ton of packages that turn vim/emacs into this ultra featureful tool. The problem is that you now have a ton of moving parts in which updates are bleeding edge - straight from the git repo.
> 
> My experience when I used Spacemacs is that I tried it for a week and it was fine. Than I installed it on another machine and a package was causing a weird error. Then while troubleshooting I went to my first machine and re-installed to see if the issue pops up and it did.
> 
> I think the solution to this would be to have the distribution creators host their own package repositories that include stable, tested versions of packages. I think Spacemacs is actually working on doing just this.
> 
> With Emacs and Vim, I can mostly recommend configuring things yourself. Especially with Vim because, IMO, it takes a lot less configuration to create a sane editor than Emacs (And I'm saying that as an Emacs user).

**Comment by pct960** [comment]
Although I do agree, the only plugin where I can pull from the latest release is ``NERDTree``. The other plugins' releases are either very old or they don't have releases at all. (``lightline``) Will reopen this issue when there are problems due to this design.
